### ISSUE TITLE
Add an option to disable old CSP headers support

### ISSUE THREAD

**Issue by MrPropre** [middlewares/csp#1]
@oscarotero Hello,

Could you please add an option to disable old CSP headers ?

```php
return $this->builder->injectCSPHeader($response, true);
```
This function (line 46) has a `$legacy` parameter (the second parameter) to add old CSP headers for legacy devices. In `middlewares/csp` this parameter is set to true, but I don't need to support old CSP headers because my website is not built to support old browsers. So, I just don't need to set this parameter to `true`, so please add an option to disable it.

Thank you in advance !

**Comment by oscarotero** [comment]
Good idea!
I just added this option and released v3.1.0 🎉
